### PR TITLE
[irods/irods#6412] Bump version to 4.3.1 (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Review by SwooshyCueb — APPROVED** [review]

**Comment by trel** [comment]
please see #24

**Review by alanking — COMMENTED** [review]
I'm guessing that this is dependent on #24 since a lot of other work needs to happen to build against 4.3.0 (if not 4.3.1)?

**Comment by korydraughn** [comment]
This was handled by #34.

Closing.

**Comment by trel** [comment]
okay, so #24 is moot.

**Pull request closed without merging**
