### PR TITLE
[irods/irods#7531] bump irods version requirement and remove exact requirement (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7531

Merge irods/irods#7536 before merging this.

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]

**Review by alanking — APPROVED** [review]
\# it when ready

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by alanking** [comment]
I believe merging https://github.com/irods/irods_netcdf/pull/50 caused a conflict with this. Needs a rebase?

**Comment by alanking** [comment]
Oof. I should've caught that. Thanks.

**Pull request merged**
