### PR TITLE
Updating NetCDF plugin for iRODS 4.2.8

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by trel** [comment]
remember to avoid the # signs :)

**Comment by d-w-moore** [comment]
ok will go ahead and squash

**Comment by d-w-moore** [comment]
Should I "#" the 17 yet? Or should we review the code before release?

**Comment by trel** [comment]
squash if you want - please don't # yet

i was referring to the accidental link to issue 2 - that's all.

**Comment by d-w-moore** [comment]
understood

**Comment by trel** [comment]
are we ready to # these and get them released as 4.2.8.0?     and then shortly afterwards... get them bumped for 4.2.9.0?

**Comment by d-w-moore** [comment]
Yes, I have to number these and that's an official, working 4.2.8.0. Then pull the commits from [this branch](https://github.com/d-w-moore/irods_netcdf/tree/update_for_4.2.9) with updates for 4.2.9 for a working 4.2.9.0

**Comment by trel** [comment]
let's make it so.   thanks.

**Pull request merged**
