### PR TITLE
[irods/irods#7265,#11,#41,#43,#45,#46,#47] Rewrite CMake, do some housekeeping, restore missing hdf5 instrumentation, fix some undefined symbols

### PR DESCRIPTION
**Pull request by SwooshyCueb**
This PR does a few things:
- Re-written CMake (irods/irods#7265)
    - NOTE: By default, the linker will now produce an error if there are undefined symbols. **This PR does not address all the undefined symbols**, but there are open issues for them. Modules that try to reference undefined symbols have been commented out in the CMake.
    - NOTE: package names have not changed, but package filenames have.
- Minor clutter cleanup (#11)
    - removed empty READMEs
    - removed old buildsystem remnants
    - consolidated LICENSE files
- Fixed `#include`s (#46, #47)
- Restored missing parts of the hdf5 instrumentation (#45)
- Fixes for a few undefined symbols (#41, #43)

clang-format and codacy will be unhappy, but none of the C++ code added in this PR is actually new code, and formatting/refactoring existing code falls outside the scope of this PR.

### CODE REVIEW

**Comment by korydraughn** [comment]
Excellent work!

Has this been tested?

> NOTE: package names have not changed, but package filenames have.

It wasn't clear to me what you meant here. Please explain the difference between a package name and a package filename.

**Comment by SwooshyCueb** [comment]
> Has this been tested?

Not yet.

> Please explain the difference between a package name and a package filename.

The package manager uses the package's name to identify it. The package's filename is just its filename, which the package manager doesn't really care about.

**Comment by trel** [comment]
I think RPM does care a bit about the filename - more than APT.

**Comment by SwooshyCueb** [comment]
> I think RPM does care a bit about the filename - more than APT.

There are conventions for rpm package filenames, just like there are for deb packages, but `rpm` itself, like `dpkg`, doesn't actually care about the filename. From [Maximum RPM: Taking the RPM Package Manager to the Limit](http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html) (emphasis mine):
> While **RPM will run just as well if a package file has been renamed**, when the packages are created during RPM's build process, they follow a specific naming convention. 

Moreover, with this PR, the package filenames will follow the proper conventions.

**Comment by trel** [comment]
excellent.

**Comment by SwooshyCueb** [comment]
Tests pass when run manually, but I couldn't get them to pass with the testing environment, even with tip of main.

**Comment by korydraughn** [comment]
Have you looked over the irods_consortium_test_hook python script to see if it needs a tweak?

@d-w-moore Please pull this PR and try running the consortium test hook to see if it works for you.

**Comment by SwooshyCueb** [comment]
I have looked at the script and nothing jumps out at me as particularly problematic. Honestly, I've never had much success running plugin tests with the testing environment.

**Comment by alanking** [comment]
I'll try to take a look at this today. What I've seen so far seems good

**Comment by SwooshyCueb** [comment]
Was finally able to get the tests to pass in the testing environment. Turns out I was naming my package directories wrongly

**Comment by korydraughn** [comment]
Excellent!

Let's wait for @alanking or @d-w-moore to see success before pounding.

@SwooshyCueb If you need to tweak a commit message/issue-number or squash anything, feel free to proceed.

**Review by alanking — APPROVED** [review]
Everything looks good to me.

Only thing I noticed is the include guards are using `_H` instead of `_HPP` in many instances, but I am not sure that's even worth addressing.

**Comment by korydraughn** [comment]
Let's capture that in an issue and handle it later.

@alanking @d-w-moore Were you able to run the tests and see them pass?

**Comment by alanking** [comment]
I can try running the tests. Don't think I've ever done that before

**Comment by korydraughn** [comment]
Yes, either you or @d-w-moore please.

Having one other person see passing tests means we can be confident about releasing this.

**Comment by d-w-moore** [comment]
@alanking - It shouldn't be different from building and running tests for the other plugins. I'm giving it a go now....

**Comment by d-w-moore** [comment]
I've now built and run irods_netcdf (with all passing results) **ubuntu18** and **centos7** targets. Can run more tomorrow if desired.

**Comment by korydraughn** [comment]
@SwooshyCueb Please make sure issue numbers are correct and add the pound it.

@d-w-moore We'll get this merged today. Once that happens, please go through the rest of the OS in the 4.3.1 release matrix/spreadsheet and update accordingly.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by d-w-moore** [comment]
Passed
---
- [ ] ubuntu18  / postgres
- [ ] ubuntu20 / postgres14
- [ ] ubuntu22 / postgres14
---
Failed
---
Upcoming (Not Yet Tested)
---
- [ ] almalinux8 / postgres
- [ ] rocky9 / postgres14
- [ ] debian11 / postgres
- [ ] debian12 / postgres14

**Pull request merged**
